# Generated by Django 3.1.4 on 2020-12-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0002_billingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_product', to='mainadmin.product')),
            ],
        ),
    ]
