# Generated by Django 3.1.4 on 2020-12-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0003_auto_20201221_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainadmin.customuser'),
            preserve_default=False,
        ),
    ]
