# Generated by Django 3.1.4 on 2020-12-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0004_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='tracking_status',
            field=models.IntegerField(default=1),
        ),
    ]
