# Generated by Django 3.1.4 on 2020-12-22 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0005_orderitems_tracking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateandtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
